---
openstack_venv: "{{ ansible_facts.user_dir }}/deployment/venvs/openstack-config"

openstack_projects:
  - "{{ openstack_compute_project }}"

openstack_compute_project:
  name: compute
  description: OpenStack compute project
  project_domain: default
  user_domain: default
  users: "{{ openstack_compute_users }}"
  keypairs:
    - name: id_ed25519
      public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL2cjqHGRy/X+vefWl1+U+ISoWlbRo02hFDb4jwBfjN2 jack@muon
  quotas: "{{ openstack_unlimited_quotas }}"

openstack_compute_users:
  - name: jackphodgkiss
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36353031613965336139373832636365663933333538346166383266613364636631663838363039
          6632636635336463653562316335386663376261656662390a313238636466326431633436373437
          35633635666539343033633836353866323237386336623733316163343063633635666362613031
          6631346161336666630a386461373634383031666535633161386633613663663963636163356238
          62306530383763613334343233626138633465656662653033303662363166356537
    email: identity@jackhodgkiss.uk
    roles: "{{ openstack_admin_roles }}"

openstack_admin_roles:
  - admin
  - heat_stack_owner
  - load-balancer_admin

openstack_user_roles:
  - member
  - heat_stack_owner
  - load-balancer_member
  - observer

openstack_unlimited_quotas:
  backup_gigabytes: -1
  backups: -1
  cores: -1
  floatingip: -1
  gigabytes: -1
  injected_file_size: -1
  injected_files: -1
  instances: -1
  key_pairs: -1
  per_volume_gigabytes: -1
  ram: -1
  security_group: -1
  security_group_rule: -1
  snapshots: -1
  volumes: -1

openstack_flavors:
  - "{{ openstack_flavor_m1_tiny }}"
  - "{{ openstack_flavor_m1_small }}"
  - "{{ openstack_flavor_m1_medium }}"
  - "{{ openstack_flavor_m1_large }}"
  - "{{ openstack_flavor_m1_xlarge }}"
  - "{{ openstack_flavor_g1_xlarge }}"

openstack_flavor_m1_tiny:
  name: "m1.tiny"
  ram: 512
  disk: 1
  vcpus: 1

openstack_flavor_m1_small:
  name: "m1.small"
  ram: 2048
  disk: 40
  vcpus: 1

openstack_flavor_m1_medium:
  name: "m1.medium"
  ram: 4096
  disk: 60
  vcpus: 2

openstack_flavor_m1_large:
  name: "m1.large"
  ram: 8192
  disk: 80
  vcpus: 4

openstack_flavor_m1_xlarge:
  name: "m1.xlarge"
  ram: 16384
  disk: 100
  vcpus: 6

openstack_flavor_g1_xlarge:
  name: "g1.xlarge"
  ram: 16384
  disk: 100
  vcpus: 6
  extra_specs:
    pci_passthrough:alias: "rtx-2070-super:1"

# List of additional host packages.
os_images_package_dependencies_extra:
  # debootstrap is required to build ubuntu-minimal images.
  - debootstrap

# Drop cloud-init and stable-interface-names from default elements.
os_images_common: enable-serial-console

# Set this to true to force rebuilding images.
os_images_force_rebuild: false

openstack_images:
  - "{{ openstack_image_ubuntu_2204_lvm }}"
  - "{{ openstack_image_rocky_9_lvm }}"
  - "{{ openstack_image_cirros_0_6_2 }}"
  - "{{ openstack_image_ubuntu_2204 }}"
  - "{{ openstack_image_ubuntu_2404 }}"

openstack_image_ubuntu_2204_lvm:
  name: "Ubuntu-22.04-LVM"
  type: qcow2
  is_public: True
  elements:
    - "cloud-init"
    - "cloud-init-datasources"
    - "cloud-init-growpart"
    - "dhcp-all-interfaces"
    - "grub2"
    - "lvm"
    - "openssh-server"
    - "ubuntu-minimal"
    - "vm"
  packages:
    - apt-utils
    - bash-completion
    - btop
    - curl
    - debootstrap
    - git
    - iputils-ping
    - less
    - linux-firmware
    - logrotate
    - lshw
    - man-db
    - net-tools
    - netbase
    - python3-venv
    - tmux
    - vim
  properties:
    os_type: "linux"
    os_distro: "ubuntu"
    os_version: "jammy"
    hw_rng_model: "virtio"
  env:
    DIB_RELEASE: "jammy"
    DIB_CLOUD_INIT_DATASOURCES: "OpenStack"
    DIB_CLOUD_INIT_GROWPART_DEVICES:
      - /dev/vda3
    DIB_BOOTLOADER_DEFAULT_CMDLINE: "nofb nomodeset gfxpayload=text rd.auto intremap=nosid net.ifnames=0"
    DIB_BLOCK_DEVICE_CONFIG: |
      - local_loop:
          name: image0
          size: 8GiB
      - partitioning:
          base: image0
          label: gpt
          partitions:
            - name: ESP
              type: 'EF00'
              size: 128MiB
              mkfs:
                type: vfat
                mount:
                  mount_point: /boot/efi
                  fstab:
                    options: "defaults"
                    fsck-passno: 2
            - name: BSP
              type: 'EF02'
              size: 8MiB
            - name: root
              type: '8E00'
              flags: [ boot ]
              size: 100%
      - lvm:
          name: lvm
          base: [ root ]
          pvs:
            - name: rootpv
              base: root
              options: [ "--force" ]
          vgs:
            - name: vg
              base: [ "rootpv" ]
              options: [ "--force" ]
          lvs:
            - name: lv_root
              base: vg
              size: 3.5G
            - name: lv_tmp
              base: vg
              size: 0.75G
            - name: lv_var
              base: vg
              size: 1G
            - name: lv_var_tmp
              base: vg
              size: 1G
            - name: lv_log
              base: vg
              size: 128M
            - name: lv_audit
              base: vg
              size: 64M
            - name: lv_home
              base: vg
              size: 0.25G
      - mkfs:
          name: fs_root
          base: lv_root
          type: ext4
          label: "rootfs"
          mount:
            mount_point: /
            fstab:
              options: "defaults"
              fsck-passno: 1
      - mkfs:
          name: fs_tmp
          base: lv_tmp
          type: ext4
          label: "tmpfs"
          mount:
            mount_point: /tmp
            fstab:
              options: "rw,nosuid,nodev"
              fsck-passno: 2
      - mkfs:
          name: fs_var
          base: lv_var
          type: ext4
          label: "varfs"
          mount:
            mount_point: /var
            fstab:
              options: "defaults"
              fsck-passno: 2
      - mkfs:
          name: fs_var_tmp
          base: lv_var_tmp
          type: ext4
          label: "vartmpfs"
          mount:
            mount_point: /var/tmp
            fstab:
              options: "rw,noexec,nosuid,nodev"
              fsck-passno: 2
      - mkfs:
          name: fs_log
          base: lv_log
          type: ext4
          label: "logfs"
          mount:
            mount_point: /var/log
            fstab:
              options: "defaults"
              fsck-passno: 2
      - mkfs:
          name: fs_audit
          base: lv_audit
          type: ext4
          label: "auditfs"
          mount:
            mount_point: /var/log/audit
            fstab:
              options: "defaults"
              fsck-passno: 2
      - mkfs:
          name: fs_home
          base: lv_home
          type: ext4
          label: "homefs"
          mount:
            mount_point: /home
            fstab:
              options: "rw,nodev"
              fsck-passno: 2

openstack_image_rocky_9_lvm:
  name: "Rocky-9-LVM"
  type: qcow2
  is_public: True
  elements:
    - "rocky-container"
    - "dracut-regenerate"
    - "cloud-init"
    - "cloud-init-growpart"
    - "epel"
    - "elrepo"
    - "selinux-permissive"
    - "dhcp-all-interfaces"
    - "vm"
    - "grub2"
    - "openssh-server"
  packages:
    - apt-utils
    - bash-completion
    - btop
    - elrepo-release
    - git
    - iputils
    - less
    - linux-firmware
    - logrotate
    - lshw
    - man-db
    - net-tools
    - python3
    - tmux
    - vim
  properties:
    os_type: "linux"
    os_distro: "rocky"
    os_version: "9"
    hw_rng_model: "virtio"
  env:
    DIB_RELEASE: "9"
    DIB_CONTAINERFILE_RUNTIME: docker
    DIB_CONTAINERFILE_RUNTIME_ROOT: 1
    DIB_CONTAINERFILE_NETWORK_DRIVER: host
    DIB_CLOUD_INIT_DATASOURCES: "OpenStack"
    DIB_CLOUD_INIT_GROWPART_DEVICES:
      - /dev/vda3
    DIB_BOOTLOADER_DEFAULT_CMDLINE: "nofb nomodeset gfxpayload=text rd.auto intremap=nosid net.ifnames=0"
    DIB_BLOCK_DEVICE_CONFIG: |
      - local_loop:
          name: image0
          size: 8GiB
      - partitioning:
          base: image0
          label: gpt
          partitions:
            - name: ESP
              type: 'EF00'
              size: 128MiB
              mkfs:
                type: vfat
                mount:
                  mount_point: /boot/efi
                  fstab:
                    options: "defaults"
                    fsck-passno: 2
            - name: BSP
              type: 'EF02'
              size: 8MiB
            - name: root
              type: '8E00'
              flags: [ boot ]
              size: 100%
      - lvm:
          name: lvm
          base: [ root ]
          pvs:
            - name: rootpv
              base: root
              options: [ "--force" ]
          vgs:
            - name: vg
              base: [ "rootpv" ]
              options: [ "--force" ]
          lvs:
            - name: lv_root
              base: vg
              size: 3G
            - name: lv_tmp
              base: vg
              size: 0.75G
            - name: lv_var
              base: vg
              size: 1G
            - name: lv_var_tmp
              base: vg
              size: 1G
            - name: lv_log
              base: vg
              size: 128M
            - name: lv_audit
              base: vg
              size: 64M
            - name: lv_home
              base: vg
              size: 0.25G
      - mkfs:
          name: fs_root
          base: lv_root
          type: ext4
          label: "rootfs"
          mount:
            mount_point: /
            fstab:
              options: "defaults"
              fsck-passno: 1
      - mkfs:
          name: fs_tmp
          base: lv_tmp
          type: ext4
          label: "tmpfs"
          mount:
            mount_point: /tmp
            fstab:
              options: "rw,nosuid,nodev"
              fsck-passno: 2
      - mkfs:
          name: fs_var
          base: lv_var
          type: ext4
          label: "varfs"
          mount:
            mount_point: /var
            fstab:
              options: "defaults"
              fsck-passno: 2
      - mkfs:
          name: fs_var_tmp
          base: lv_var_tmp
          type: ext4
          label: "vartmpfs"
          mount:
            mount_point: /var/tmp
            fstab:
              options: "rw,noexec,nosuid,nodev"
              fsck-passno: 2
      - mkfs:
          name: fs_log
          base: lv_log
          type: ext4
          label: "logfs"
          mount:
            mount_point: /var/log
            fstab:
              options: "defaults"
              fsck-passno: 2
      - mkfs:
          name: fs_audit
          base: lv_audit
          type: ext4
          label: "auditfs"
          mount:
            mount_point: /var/log/audit
            fstab:
              options: "defaults"
              fsck-passno: 2
      - mkfs:
          name: fs_home
          base: lv_home
          type: ext4
          label: "homefs"
          mount:
            mount_point: /home
            fstab:
              options: "rw,nodev"
              fsck-passno: 2

openstack_image_cirros_0_6_2:
  name: "Cirros-6.2"
  type: qcow2
  image_url: "https://github.com/cirros-dev/cirros/releases/download/0.6.2/cirros-0.6.2-x86_64-disk.img"
  is_public: True
  properties:
    os_type: "linux"
    os_distro: "cirros"
    os_version: "0.6.2"
    hw_rng_model: "virtio"

openstack_image_ubuntu_2204:
  name: "Ubuntu 22.04"
  type: qcow2
  image_url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
  is_public: True
  properties:
    os_type: "linux"
    os_distro: "Ubuntu"
    os_version: "22.04"
    hw_rng_model: "virtio"

openstack_image_ubuntu_2404:
  name: "Ubuntu 24.04"
  type: qcow2
  image_url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
  is_public: True
  properties:
    os_type: "linux"
    os_distro: "Ubuntu"
    os_version: "24.04"
    hw_rng_model: "virtio"

openstack_networks:
  - "{{ openstack_network_external }}"
  - "{{ openstack_network_admin_vlan }}"
  - "{{ openstack_network_compute_vlan }}"

openstack_network_external_name: "external"

openstack_network_external:
  name: "{{ openstack_network_external_name }}"
  project: "admin"
  provider_network_type: "vlan"
  provider_physical_network: "physnet1"
  provider_segmentation_id: 40
  shared: true
  external: true
  subnets:
    - "{{ openstack_subnet_external }}"

openstack_subnet_external:
  name: "{{ openstack_network_external_name }}"
  project: "admin"
  cidr: "10.0.40.0/24"
  gateway_ip: "10.0.40.254"
  allocation_pool_start: "10.0.40.200"
  allocation_pool_end: "10.0.40.249"

openstack_network_admin_vlan_name: "admin-vlan"

openstack_network_admin_vlan:
  name: "{{ openstack_network_admin_vlan_name }}"
  project: admin
  provider_network_type: "vlan"
  provider_physical_network: "physnet1"
  shared: false
  subnets:
    - "{{ openstack_subnet_admin_vlan }}"

openstack_subnet_admin_vlan:
  name: "{{ openstack_network_admin_vlan_name }}"
  project: admin
  cidr: "172.20.0.0/24"
  gateway_ip: "172.20.0.254"
  allocation_pool_start: "172.20.0.1"
  allocation_pool_end: "172.20.0.253"

openstack_routers:
  - "{{ openstack_router_admin }}"
  - "{{ openstack_router_compute }}"

openstack_router_admin:
  - name: admin
    project: admin
    interfaces:
      - "{{ openstack_network_admin_vlan_name }}"
    network: "{{ openstack_network_external_name }}"

openstack_network_compute_vlan_name: "compute-vlan"

openstack_network_compute_vlan:
  name: "{{ openstack_network_compute_vlan_name }}"
  project: compute
  provider_network_type: "vlan"
  provider_physical_network: "physnet1"
  shared: false
  subnets:
    - "{{ openstack_subnet_compute_vlan }}"

openstack_subnet_compute_vlan:
  name: "{{ openstack_network_compute_vlan_name }}"
  project: compute
  cidr: "10.200.0.0/24"
  gateway_ip: "10.200.0.254"
  allocation_pool_start: "10.200.0.1"
  allocation_pool_end: "10.200.0.253"

openstack_router_compute:
  - name: compute
    project: compute
    interfaces:
      - "{{ openstack_network_compute_vlan_name }}"
    network: "{{ openstack_network_external_name }}"

openstack_security_groups:
  - name: default
    project: admin
    rules:
      - protocol: icmp
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22
  - name: default
    project: compute
    rules:
      - protocol: icmp
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22
